### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [jasmine/jasmine-ajax#143]
Pretty self-explanatory. Using your latest version on npm:

```
  TypeError: Cannot read property 'toString' of undefined
      at RequestStub.matches (/home/michael-heuberger/Development/project/node_modules/karma-jasmine-ajax/node_modules/jasmine-ajax/lib/mock-ajax.js:624:24)
      at StubTracker.findStub (/home/michael-heuberger/Development/project/node_modules/karma-jasmine-ajax/node_modules/jasmine-ajax/lib/mock-ajax.js:713:18)
      at FakeXMLHttpRequest.extend.send (/home/michael-heuberger/Development/project/node_modules/karma-jasmine-ajax/node_modules/jasmine-ajax/lib/mock-ajax.js:331:32)
      at asyncRequest (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:55483:21)
      at Object.Ext.lib.Ajax.pub.request (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:55538:21)
      at Ext.extend.request (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:7017:52)
      at Ext.define.requestPromise (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:76152:15)
      at Ext.define.sync (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:58890:39)
      at Ext.define.fetch (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:58762:18)
      at Object.<anonymous> (/home/michael-heuberger/Development/project/target/resources/public/scripts/jasmine.js:181728:24)
```

**Comment by slackersoft** [comment]
This error should only occur when attempting to `open` a request with no url provided. Since this would be an invalid request, the only thing we would probably do to change this behavior would be to raise the error sooner (either when `open` is called without a url, or when `send` is called without being `open`ed.

We'd be happy to review a pull request that throws appropriate errors closer to the place at which the error takes place.

**Comment by slackersoft** [comment]
After a bit more research, it turns out a call to `open()` with a `null` or `undefined` value for `url` is actually valid from the `XMLHttpRequest` objects perspective, so if Jasmine-Ajax wants to maintain compatibility with the spec, we should just convert to a string with ` + ''` or something.
