### ISSUE TITLE
3.3.0 is causing: Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by hansede** [jasmine/jasmine-ajax#168]
My webpack build is failing when building jasmine-ajax after the release of 3.3.0 today. Here is the error:

```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'fs' in /node_modules/jasmine-core/lib
    at /node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /node_modules/async/lib/async.js:726:13
    at /node_modules/async/lib/async.js:52:16
    at done (/node_modules/async/lib/async.js:241:17)
    at /node_modules/async/lib/async.js:44:16
    at /node_modules/async/lib/async.js:723:17
    at /node_modules/async/lib/async.js:167:37
    at /node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /node_modules/tapable/lib/Tapable.js:134:6
    at /node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /node_modules/tapable/lib/Tapable.js:134:6
    at /node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:31:26)
    at /node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /node_modules/enhanced-resolve/lib/FileAppendPlugin.js:28:12
    at Storage.finished (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:82:15)
resolve module fs in /node_modules/jasmine-core/lib
  looking for modules in /node_modules
    /node_modules/fs doesn't exist (module as directory)
    resolve 'file' fs in /node_modules
      resolve file
        /node_modules/fs doesn't exist
        /node_modules/fs.js doesn't exist
        /node_modules/fs.jsx doesn't exist
        /node_modules/fs.scss doesn't exist
  looking for modules in /node_modules
    /node_modules/fs doesn't exist (module as directory)
    resolve 'file' fs in /node_modules
      resolve file
        /node_modules/fs doesn't exist
        /node_modules/fs.js doesn't exist
        /node_modules/fs.jsx doesn't exist
        /node_modules/fs.scss doesn't exist
```

**Comment by hansede** [comment]
Switching back to 3.2.0 resolved the issue.
