### ISSUE TITLE
how to install jasmine-ajax with jasmine

### ISSUE THREAD

**Issue by unixc3t** [jasmine/jasmine-ajax#195]
## Expected Behavior
jasmine.Ajax.install can work

## Current Behavior
can't work,ReferenceError: getJasmineRequireObj is not defined

when I use npm run test:unit tests/unit/backend/axios.spec.js 
```javascript
ReferenceError: getJasmineRequireObj is not defined
    at /home/rudy/projects/vscode/recordstore-front/dist/webpack:/node_modules/jasmine-ajax/lib/mock-ajax.js:43:1
    at Object../node_modules/jasmine-ajax/lib/mock-ajax.js (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/node_modules/jasmine-ajax/lib/mock-ajax.js:45:1)
    at __webpack_require__ (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/webpack/bootstrap:19:1)
    at Module../tests/unit/backend/axios.spec.js (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/tests/unit/backend/axios.spec.js:1:1)
    at __webpack_require__ (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/webpack/bootstrap:19:1)
    at run (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/node_modules/mocha-webpack/lib/entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mocha-webpack/lib/entry.js (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/node_modules/mocha-webpack/lib/entry.js:10:1)
    at __webpack_require__ (/home/rudy/projects/vscode/recordstore-front/dist/webpack:/webpack/bootstrap:19:1)
    at /home/rudy/projects/vscode/recordstore-front/dist/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/rudy/projects/vscode/recordstore-front/dist/main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object._module2.default._extensions.<computed> [as .js] (/home/rudy/projects/vscode/recordstore-front/node_modules/mocha-webpack/lib/util/registerRequireHook.js:148:12)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/rudy/projects/vscode/recordstore-front/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/rudy/projects/vscode/recordstore-front/node_modules/mocha/lib/mocha.js:576:10)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/mocha-webpack/lib/runner/TestRunner.js:191:27
    at /home/rudy/projects/vscode/recordstore-front/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/rudy/projects/vscode/recordstore-front/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at AsyncSeriesHook.lazyCompileHook (/home/rudy/projects/vscode/recordstore-front/node_modules/tapable/lib/Hook.js:154:20)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:261:22
    at Compiler.emitRecords (/home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:375:39)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:255:10
    at /home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:361:14
    at eval (eval at create (/home/rudy/projects/vscode/recordstore-front/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at callback (/home/rudy/projects/vscode/recordstore-front/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (/home/rudy/projects/vscode/recordstore-front/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/rudy/projects/vscode/recordstore-front/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/home/rudy/projects/vscode/recordstore-front/node_modules/tapable/lib/Hook.js:154:20)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:358:27
    at /home/rudy/projects/vscode/recordstore-front/node_modules/neo-async/async.js:2825:7
    at done (/home/rudy/projects/vscode/recordstore-front/node_modules/neo-async/async.js:2861:11)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/neo-async/async.js:2813:7
    at MemoryFileSystem.writeFile (/home/rudy/projects/vscode/recordstore-front/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:342:29)
    at /home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:352:7
    at baseEach (/home/rudy/projects/vscode/recordstore-front/node_modules/neo-async/async.js:2416:9)
    at Object.each (/home/rudy/projects/vscode/recordstore-front/node_modules/neo-async/async.js:2850:9)
    at emitFiles (/home/rudy/projects/vscode/recordstore-front/node_modules/webpack/lib/Compiler.js:315:13)
    at Immediate._onImmediate (/home/rudy/projects/vscode/recordstore-front/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at processImmediate (internal/timers.js:439:21)

 ERROR  mocha-webpack exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! recordstore-front@0.1.0 test:unit: `vue-cli-service test:unit "tests/unit/backend/axios.spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the recordstore-front@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rudy/.npm/_logs/2019-05-09T06_28_01_317Z-debug.log

```

## Possible Solution

I try this #178 ,but it can't work

## Suite that reproduces the behavior (for bugs)
vue create name
install jasmine, jasmine-ajax
npm run test:unit tests/unit/backend/axios.spec.js 

 this is my axios.spec.js
when I run npm run test:unit tests/unit/backend/axios.spec.js
```javascript
import jasmine from 'jasmine'
import 'jasmine-ajax'

describe('create instance', done => {
  beforeEach(function () {
    jasmine.Ajax.install()
  })

  afterEach(function () {
    jasmine.Ajax.uninstall()
  })

  it('test baseUrl', () => {
    console.log(jasmine)
  })
})

```
```javascript
{
  "name": "recordstore-front",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:e2e": "vue-cli-service test:e2e",
    "test:unit": "vue-cli-service test:unit"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-axios": "^2.1.4",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-e2e-nightwatch": "^3.7.0",
    "@vue/cli-plugin-eslint": "^3.7.0",
    "@vue/cli-plugin-unit-mocha": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.1",
    "chai": "^4.1.2",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "jasmine": "^3.4.0",
    "jasmine-ajax": "^4.0.0",
    "jasmine-core": "^3.4.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "tailwindcss": "^0.7.4",
    "vue-template-compiler": "^2.5.21"
  }
}
```
## Context

I want to test request headers, so I want to mock a ajax and test request headers

## Your Environment

node version: v12.1.0
vue-cli verions: 3.7.0

**Comment by slackersoft** [comment]
Based on this message: `ERROR  mocha-webpack exited with code 1.`, and the rest of the stacktrace, it looks like you're actually using Mocha to execute your specs and not Jasmine. See the [Vue-CLI Unit Testing Docs](https://cli.vuejs.org/config/#unit-testing). It doesn't look like that toolkit currently supports using Jasmine, so you might have to talk to them about what is needed for support.

**Comment by unixc3t** [comment]
@slackersoft  thank you
