### ISSUE TITLE
AJAX immediately returning an error in IE10

### ISSUE THREAD

**Issue by rawling** [jasmine/jasmine-ajax#78]
I have succesfully mocked out AJAX calls in several tests when run in FireFox.

However, when running in IE10, after calling $.ajax control passes straight to the error callback.

The first parameter is `{ readyState: 0, status: 0. statusText: "Error: The system cannot locate the resource specified." }` and the second parameter is a similar message.

The third parameter has the message again, a "number" of -2146697211 and a stack of:

    Error: The system cannot locate the resource specified.
     at send (file:///x/Scripts/jquery-1.10.2.js:8720:6)
     at ajax (file:///x/Scripts/jquery-1.10.2.js:8150:5)
     at DoSearch (file:///x/Scripts/lkg-multilicense.js:155:17)
     at Anonymous function (file:///x/Web/Jasmine/spec/MultiLicenseSpec.js:843:25)
     at attemptSync (file:///x/Web/Jasmine/lib/jasmine-2.0.2/jasmine.js:1620:9)
     at run (file:///x/Web/Jasmine/lib/jasmine-2.0.2/jasmine.js:1608:9)
     at execute (file:///x/Web/Jasmine/lib/jasmine-2.0.2/jasmine.js:1595:5)
     at queueRunnerFactory (file:///x/Web/Jasmine/lib/jasmine-2.0.2/jasmine.js:508:7)
     at execute (file:///x/Web/Jasmine/lib/jasmine-2.0.2/jasmine.js:295:5)
     at Anonymous function (file:///x/Web/Jasmine/lib/jasmine-2.0.2/jasmine.js:1834:31)

I'm using Jasmine 2.0.2 and the currently-28-day-old version of mock-ajax.js.

**Comment by slackersoft** [comment]
We haven't heard of anyone else with this issue and we haven't been able to reproduce it. It sounds like it might be a setup issue with IE 10 and `file:///` protocols so I'm going to close it. If you have any new info please let us know.
